<?php $title='Our Team' ; include($_SERVER[ 'DOCUMENT_ROOT']. '/required/header.php'); include($_SERVER[ 'DOCUMENT_ROOT']. '/required/navigation.php'); ?>

<!-- begin page content -->
<div class='pagebody clearfix'>
    <div class='content-container'>
        <div class='pageheader'>
            <h1>Oral Prophylaxis</h1>
        </div>
        <div class='pagecontent clearfix'>
            <div class = 'service_desc'>
                <p>is a procedure done for teeth cleaning. It removes tartar and plaque build-up from the surfaces of the teeth as well as those hidden in between and under the gums. The dentist uses a scaler, a type of hand instrument, to remove the plaque and tartar.</p>
            </div>
            <div class = 'service_body'>
                <h4 class='blueline'>Advantages</h4>
                <ol>
                    <li>It minimizes the operator and patient fatigue.</li>
                    <li>It is time saving and effective.</li>
                    <li>Dentinal sensitivity is diminished following the use of prophy-jet, which may be explained by the fact that bicarbonate crystals may block the tubular opening</li>
                    <li>4.  It removes plaque from areas that are otherwise difficult to reach like furcations, flutings and close root proximities.</li>
                </ol>
                <h4 class='blueline'>Disadvantages</h4>
                <ol>
                    <li>They should be cautiously used in patients with restricted sodium diets, respiratory, renal or metabolic disease, infectious disease, children, diuretics or long term steroid therapy, and those having titanium implants. Owing to the limitation of prophy-jet in individuals with sodium restricted diets, nonsodium prophy powder, containing aluminum trihydroxide (cavitron, jet-fresh) instead of sodium bicarbonate can be used</li>
                    <li>Another drawback is the aerosols generated by air-polishing may present an infection control hazard. Hence, a preprocedural rinse is always recommended along with aerosol reduction devices. Subcutaneous emphysema can also occur whenever compressed air is employed intra-orally. This highlights the iatrogenic potential and reinforces the need to follow manufacturer's instructions appropriately.</li>
                </ol>
                <h4 class='blueline'>Conclusion</h4>
                <p>Tooth polishing used to be a standard part of a dental cleaning appointment. The dentists used to smoothen teeth so that plaque and bacteria which cause gingivitis, periodontitis or cavities do not stick to the tooth easily. However, it is now known that within 30 min, the bacteria colonize on the tooth surface irrespective of whether teeth are polished or not. Also, polishing removes the outer layer of tooth enamel, which takes a period of 3 months to rebuild the fluoride-rich layer. Hence, selective polishing is recommended. Each patient should be assessed individually for polishing of teeth. Teeth are polished only if stains are present which scaling was unable to remove. This means that during cleaning procedures either some, all or none of the teeth may be polished.<br><br>
                Currently, the dentists and hygienists have varied options regarding the abrasive/polishing agents and type of polishers used. They can now use different polishers and abrasives based on the patients’ acceptance and condition, thereby providing good care by selectively designing the treatment according to the patients’ need and with minimum concern about the loss of tooth structure.
                </p>
            </div>
        </div>
    </div>
</div>
<!-- end page content -->

<?php include($_SERVER[ 'DOCUMENT_ROOT']. '/required/footer.php'); ?>